//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.29 at 02:16:45 AM COT 
//


package com.defaults.marketplace.apigateway.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.defaults.marketplace.productsearch.entities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ServiceSOAP_QNAME = new QName("http://www.defaults.com/marketplace/productSearch/entities", "serviceSOAP");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.defaults.marketplace.productsearch.entities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceSOAP }
     * 
     */
    public ServiceSOAP createServiceSOAP() {
        return new ServiceSOAP();
    }

    /**
     * Create an instance of {@link SearchServicesRequest }
     * 
     */
    public SearchServicesRequest createSearchServicesRequest() {
        return new SearchServicesRequest();
    }

    /**
     * Create an instance of {@link SearchServicesResponse }
     * 
     */
    public SearchServicesResponse createSearchServicesResponse() {
        return new SearchServicesResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceSOAP }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ServiceSOAP }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.defaults.com/marketplace/productSearch/entities", name = "serviceSOAP")
    public JAXBElement<ServiceSOAP> createServiceSOAP(ServiceSOAP value) {
        return new JAXBElement<ServiceSOAP>(_ServiceSOAP_QNAME, ServiceSOAP.class, null, value);
    }

}
