//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.29 at 02:16:45 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.defaults.com/marketplace/productSearch/entities", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.defaults.marketplace.apigateway.schema;
