//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.29 at 02:16:45 AM COT 
//


package com.defaults.marketplace.apigateway.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serviceCategory.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="serviceCategory"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="TRANSPORTATION"/&gt;
 *     &lt;enumeration value="LODGING"/&gt;
 *     &lt;enumeration value="MEAL"/&gt;
 *     &lt;enumeration value="TOUR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "serviceCategory")
@XmlEnum
public enum ServiceCategory {

    TRANSPORTATION,
    LODGING,
    MEAL,
    TOUR;

    public String value() {
        return name();
    }

    public static ServiceCategory fromValue(String v) {
        return valueOf(v);
    }

}
